services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 2001:2001
    network_mode: 'host'
    volumes:
      - /opt/jellyfin/config:/config
      - /opt/jellyfin/cache:/cache
      - type: bind
        source: /opt/jellyfin/media
        target: /media
        read_only: true
    restart: 'unless-stopped'
    extra_hosts:
      - 'host.docker.internal:host-gateway'